spring.application.name=portfolios

server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/portfolio
spring.data.mongodb.database=portfolio
spring.data.mongodb.auto-index-creation=true


finnhub.api-key=d5ihg7pr01qo1lb23dqgd5ihg7pr01qo1lb23dr0
finnhub.base-url=https://finnhub.io/api/v1
gmial.app.key=xehs mpyx dlya qpja
gmial.app.pass = spring
gmial.app.pass=opplspuvrfntpepg

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bgm00ind@gmail.com
spring.mail.password=opplspuvrfntpepg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

api.base.url=http://localhost:8080

